CheckList/Controllers/CheckListController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CheckList.Models;
using CheckList.Models.CheckList;
using CheckList.Models.CheckListItem;
using CheckList.ResquestModel.CheckList;
using CheckList.ViewModel.CheckList;


namespace CheckList.Controllers
{
    public class CheckListController : Controller
    {
        private readonly ILogger<CheckListController> _logger;
        private readonly CheckListService _checkListService;

        public CheckListController(ILogger<CheckListController> logger, CheckListService checkListService)
        {
            _logger = logger;
            _checkListService = checkListService;
        }

        public IActionResult Listagem() //listagem
        {
            var viewModel = new ListagemViewModel()
            {
                msgSucesso = (string)TempData["formMsgSucesso"],
                msgErro = (string[])TempData["formMsgErros"]
            };

            var listaCheckList = _checkListService.ObterTodo();
            
            foreach ( CheckListEntity checkListEntity in listaCheckList)
            {
                viewModel.CheckLists.Add(new CheckLists()
                {
                    id = checkListEntity.id.ToString(),
                    nome = checkListEntity.nome
                });
                
            }

            return View(viewModel);
        }
        
        [HttpGet] //mostrar para o usuario o formulario
        public IActionResult Adicionar()
        {  
            var viewModel = new AdicionarViewModel()
            {
                msgErros = (string[]) TempData["formMsgErros"]
            };
            
            return View(viewModel);
        }
        
        [HttpPost] //processar o formulario enviado para o usuario
        public RedirectToActionResult Adicionar(AdicionarRequestModel requestModel)
        {
            var nome = requestModel.Nome;
            
            var listaErros = requestModel.ValidarEFiltrar();

            if (listaErros.Count > 0)
            {
                TempData["formMsgErro"] = listaErros;

                return RedirectToAction("Adicionar");
            }

            try
            {
                _checkListService.Adicionar(requestModel);
                TempData["formMsgSucesso"] = "Checklist adicionada com sucesso!!";

               
                return RedirectToAction("Listagem");
            }
            catch (Exception e)
            {

                TempData["formMsgErros"] = new List<string> {e.Message};
                
                return RedirectToAction("Adicionar");
            }

        }
        
        [HttpGet]
        public IActionResult Editar(int id)
        {
            try
            {
                var entidadeAEditar = _checkListService.ObterPorId(id);
                
                var viewModel = new EditarViewModel()
                {
                    msgErros = (string[]) TempData["formMsgErros"],
                    id = entidadeAEditar.id.ToString(),
                    Nome = entidadeAEditar.nome
                };

                return View(viewModel);
            }
            catch (Exception e)
            {
                TempData["formMsgErros"] = new List<string> { e.Message };

                return RedirectToAction("Listagem");
            }            
        }
        
        [HttpPost]
        public RedirectToActionResult Editar(int id, EditarRequestModel requestModel)
        {
            Console.WriteLine(id);
            var listaErros = requestModel.ValidarEFiltrar();
            
            if (listaErros.Count > 0)
            {
                TempData["formMsgErro"] = listaErros;

                return RedirectToAction("Editar");
            }
            try
            {
                _checkListService.Editar(id ,requestModel);
                TempData["formMsgSucesso"] = "CheckList editados com sucesso.";
                
                return RedirectToAction("Listagem");
            }
            catch (Exception exception)
            {

                TempData["formMsgErros"] = new List<string> { exception.Message };
                
                return RedirectToAction("Editar");
            }
        }
        
        public IActionResult Remover(int id)
        {
            try
            {
                var entidadeARemover = _checkListService.ObterPorId(id); //uma variavel que pega o id que o usuario escolheu para remover
                var viewModel = new RemoverViewModel()
                {
                    msgErros = (string[]) TempData["formMsgErros"],
                    id = entidadeARemover.id.ToString(),
                    Nome = entidadeARemover.nome
                };

                return View(viewModel);
            }
            catch (Exception e)
            {
                TempData["formMsgErros"] = new List<string> { e.Message };

                return RedirectToAction("Listagem");
            }            
        }

        [HttpPost]
        public RedirectToActionResult Remover(int id, object requestModel)
        {
            try
            {
                _checkListService.Remover(id);
                TempData["formMsgSucesso"] = "CheckList removido com sucesso!!";

                return RedirectToAction("Listagem");
            }
            catch (Exception exception)
            {

                TempData["formMsgErros"] = new List<string> {exception.Message};

                return RedirectToAction("Remover");
            }

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

CheckList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - CheckList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CheckList</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CheckList" asp-action="Listagem">Checklists</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - CheckList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>